name: Clojure CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Set up Clojure
      uses: DeLaGuardo/setup-clojure@12.1
      with:
        lein: '2.11.2'

    - name: Cache Leiningen dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-lein-${{ hashFiles('project.clj') }}
        restore-keys: |
          ${{ runner.os }}-lein-

    - name: Install dependencies
      run: lein deps

    - name: Run linter
      run: lein lint

    - name: Run tests
      run: lein test